name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Build aplicação
        run: npm run build

      - name: Build imagem Docker
        run: docker build -t github-actions-ci-cd .

              - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag imagem Docker
        run: docker tag github-actions-ci-cd gabrielcardenette/github-actions-ci-cd:latest

      - name: Push imagem Docker
        run: docker push gabrielcardenette/github-actions-ci-cd:latest